version: "3.9"

services:
  app:
    container_name: api-server
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql-db
      - redis-db
    env_file:
      - env/base.env
    networks:
      - fastapi-boilerplate-network

  postgresql-db:
    container_name: postgresql-db
    image: postgres:16-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    env_file:
      - env/dev.env
    ports:
      - "5434:5432"
    networks:
      - fastapi-boilerplate-network

  redis-db:
    container_name: redis-db
    image: redis:6.0-alpine
    env_file:
      - env/dev.env
    ports:
      - "6379:6379"
    networks:
      - fastapi-boilerplate-network

volumes:
  postgresql-data:

networks:
  fastapi-boilerplate-network:
