"""init_db

Revision ID: ada508848f93
Revises:
Create Date: 2025-01-12 05:19:36.655487

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ada508848f93"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False, comment="PK"),
        sa.Column(
            "user_id", sa.String(length=256), nullable=False, comment="사용자입력ID"
        ),
        sa.Column("name", sa.String(length=256), nullable=False, comment="이름"),
        sa.Column("email", sa.String(length=256), nullable=False, comment="이메일"),
        sa.Column(
            "hashed_password",
            sa.String(length=256),
            nullable=False,
            comment="해시된 비밀번호",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True, comment="탈퇴여부"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="수정일시",
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True, comment="삭제일시"),
        sa.PrimaryKeyConstraint("id"),
        comment="회원",
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
