"""admin_add

Revision ID: af49f6576886
Revises: ada508848f93
Create Date: 2025-04-23 06:56:31.217243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af49f6576886'
down_revision: Union[str, None] = 'ada508848f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('admin_id', sa.String(length=256), nullable=False, comment='관리자 ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='이름'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='이메일'),
    sa.Column('role', sa.Enum('SUPER', 'NORMAL', name='admin_role_enum'), nullable=False, comment='관리자 권한'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False, comment='해시된 비밀번호'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='관리자'
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='탈퇴여부')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='탈퇴여부')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
