"""init_database

Revision ID: c81683dc778d
Revises:
Create Date: 2025-08-07 08:33:35.872095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81683dc778d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('admin_id', sa.String(length=256), nullable=False, comment='관리자 ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='이름'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='이메일'),
    sa.Column('role', sa.Enum('SUPER', 'NORMAL', name='admin_role_enum'), nullable=False, comment='관리자 권한'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False, comment='해시된 비밀번호'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'deleted_at', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('email', 'deleted_at', postgresql_nulls_not_distinct=True),
    comment='관리자'
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('title', sa.Text(), nullable=False, comment='제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='내용'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID(논리적 FK)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='아이템'
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('user_id', sa.String(length=256), nullable=False, comment='사용자입력ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='이름'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False, comment='해시된 비밀번호'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='탈퇴여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'deleted_at', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('user_id', 'deleted_at', postgresql_nulls_not_distinct=True),
    comment='회원'
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
