"""Initial migration

Revision ID: c8c020b75d8d
Revises:
Create Date: 2025-01-10 05:11:45.419440

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c8c020b75d8d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
