# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: boilerplate_user
          POSTGRES_PASSWORD: boilerplate
          POSTGRES_DB: boilerplate-dev-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U boilerplate_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Create .env file
        run: |
          cat <<EOF > .env
          ENV_STATE=dev
          JWT_SECRET_KEY=jwt-secret-key
          JWT_ALGORITHM=HS256
          ACCESS_TOKEN_EXPIRE_MINUTES=30
          REFRESH_TOKEN_EXPIRE_MINUTES=60
          ADMIN_ID=admin
          ADMIN_PASSWORD=admin
          REDIS_HOST=localhost
          REDIS_PORT=6379
          REDIS_DATABASE=0
          DEV_REDIS_PASSWORD=
          POSTGRES_HOST=localhost
          POSTGRES_PORT=5432
          DEV_POSTGRES_USER=boilerplate_user
          DEV_POSTGRES_PASSWORD=boilerplate
          DEV_POSTGRES_DB=boilerplate-dev-db
          DEV_DEBUG=True
          DEV_ALLOWED_ORIGINS=*
          EOF

      - name: Install dependencies (with uv)
        run: uv sync

      - name: Run Alembic migrations
        run: uv run alembic upgrade head

      - name: Run tests (with uv)
        run: uv run pytest --cov=app --cov-report=term-missing --ignore temp
